json_to_estabelecimento = ["estabelecimento.cnae.classe as classe_cnae",
                           "estabelecimento.cnae.codigoClasse as cod_classe_cnae",
                           "estabelecimento.cnae.codigoDivisao as cod_divisao_cnae",
                           "estabelecimento.cnae.codigoGrupo as cod_grupo_cnae",
                           "estabelecimento.cnae.codigoSecao as cod_secao_cnae",
                           "estabelecimento.cnae.codigoSubclasse as cod_sub_classe_cnae",
                           "estabelecimento.cnae.divisao as divisao_cnae",
                           "estabelecimento.cnae.grupo as grupo_cnae",
                           "estabelecimento.cnae.secao as secao_cnae",
                           "estabelecimento.cnae.subclasse as subclasse_cnae",
                           "estabelecimento.codigoFormatado as cpf_cnpj",
                           "estabelecimento.complementoEndereco as compl_endereco",
                           "estabelecimento.dataAbertura as data_abertura",
                           "estabelecimento.descricaoLogradouro as desc_logradouro",
                           "estabelecimento.enderecoEletronico as email",
                           "estabelecimento.localidadePessoa as localidade",
                           "estabelecimento.municipio.codigoIBGE as cod_ibge_municipio",
                           "estabelecimento.municipio.nomeIBGE as nome_ibge_municipio",
                           "estabelecimento.municipio.pais as pais",
                           "estabelecimento.municipio.uf.nome as nome_uf",
                           "estabelecimento.municipio.uf.sigla as sigla_uf",
                           "estabelecimento.naturezaJuridica.codigo as cod_nat_juridica",
                           "estabelecimento.naturezaJuridica.codigoTipo as cod_tipo_nat_juridica",
                           "estabelecimento.naturezaJuridica.descricao as desc_nat_juridica",
                           "estabelecimento.naturezaJuridica.descricaoTipo as desc_tipo_nat_juridica",
                           "estabelecimento.nome as nome",
                           "estabelecimento.nomeBairro as nome_bairro",
                           "estabelecimento.nomeFantasiaReceita as nome_fantasia",
                           "estabelecimento.numeroCEP as cep",
                           "estabelecimento.numeroEndereco as numero_rua",
                           "estabelecimento.numeroInscricaoSocial as numero_inscr_social",
                           "estabelecimento.numeroTelefone as numero_telefone",
                           "estabelecimento.tipoCodigo as tipo_documento",
                           "estabelecimento.municipio.uf.sigla as sigla_uf_part"]

json_to_unidade_gestora = ["unidadeGestora.codigo as cod_unidade_gestora",
                           "unidadeGestora.nome as nome_unidade_gestora",
                           "unidadeGestora.orgaoVinculado.cnpj as cnpj_orgao_vinculado",
                           "unidadeGestora.orgaoVinculado.codigoSIAFI as cod_siafi_orgao_vinculado",
                           "unidadeGestora.orgaoVinculado.descricaoPoder as desc_poder_orgao_vinculado",
                           "unidadeGestora.orgaoVinculado.nome as nome_orgao_vinculado",
                           "unidadeGestora.orgaoVinculado.orgaoMaximo.codigo as cod_orgao_maximo",
                           "unidadeGestora.orgaoVinculado.orgaoMaximo.nome as nome_orgao_maximo",
                           "unidadeGestora.orgaoVinculado.orgaoMaximo.sigla as sigla_orgao_maximo",
                           "unidadeGestora.orgaoVinculado.orgaoMaximo.codigo as cod_orgao_maximo_part"]

json_to_cartao_funcinario = ["portador.codigoFormatado as doc_portador",
                             "portador.nome as nome_portador",
                             "tipoCartao.codigo as cod_tipo_cartao",
                             "tipoCartao.descricao as dsc_tipo_cartao",
                             "tipoCartao.id as id_tipo_cartao",
                             "tipoCartao.codigo as cod_tipo_cartao_part"]

json_to_pagamentos = ["id as id_pagamento",
                      "to_date(dataTransacao, 'dd/MM/yyyy') as data_transacao",
                      "cast(regexp_replace(regexp_replace(valorTransacao, '\\\.', ''), ',', '.')\
                       as double) as valor_transacao",
                      "estabelecimento.dataAbertura as data_abertura_estabelecimento",
                      "estabelecimento.nome as nome_estabelecimento",
                      "estabelecimento.municipio.codigoIBGE as cod_cidade_estabelecimento",
                      "estabelecimento.municipio.uf.sigla as uf_estabelecimento",
                      "estabelecimento.codigoFormatado as cpf_cnpj_estabelecimento",
                      "portador.codigoFormatado as cpf_cnpj_portador",
                      "portador.nome as nome_portador",
                      "tipoCartao.codigo as cod_tipo_cartao",
                      "unidadeGestora.codigo as cod_unidade_gestora",
                      "substr(mesExtrato, 1, 2) as mes_extrato",
                      "substr(mesExtrato, 4, 4) as ano_extrato",
                      "substr(mesExtrato, 1, 2) as mes_extrato_part",
                      "substr(mesExtrato, 4, 4) as ano_extrato_part"
                      ]

json_to_municipio = ["estabelecimento.municipio.codigoIBGE as cod_ibge_municipio",
                     "estabelecimento.municipio.nomeIBGE as nome_ibge_municipio",
                     "estabelecimento.municipio.pais as pais",
                     "estabelecimento.municipio.uf.nome as nome_uf",
                     "estabelecimento.municipio.uf.sigla as sigla_uf",
                     "estabelecimento.municipio.uf.sigla as sigla_uf_part"]


json_to_uf = ["estabelecimento.municipio.pais as pais",
              "estabelecimento.municipio.uf.nome as nome_uf",
              "estabelecimento.municipio.uf.sigla as sigla_uf",
              "estabelecimento.municipio.uf.sigla as sigla_uf_part"]
