from pyspark.sql.types import StructType, StringType, LongType, StructField

voucher_schema = StructType([
    StructField("dataTransacao", StringType(), True),
    StructField("estabelecimento",
                StructType([
                    StructField("cnae",
                                StructType([
                                    StructField("classe", StringType(), True),
                                    StructField("codigoClasse", StringType(), True),
                                    StructField("codigoDivisao", StringType(), True),
                                    StructField("codigoGrupo", StringType(), True),
                                    StructField("codigoSecao", StringType(), True),
                                    StructField("codigoSubclasse", StringType(), True),
                                    StructField("divisao", StringType(), True),
                                    StructField("grupo", StringType(), True),
                                    StructField("secao", StringType(), True),
                                    StructField("subclasse", StringType(), True)]), True),
                    StructField("codigoFormatado", StringType(), True),
                    StructField("complementoEndereco", StringType(), True),
                    StructField("dataAbertura", StringType(), True),
                    StructField("descricaoLogradouro", StringType(), True),
                    StructField("enderecoEletronico", StringType(), True),
                    StructField("localidadePessoa", StringType(), True),
                    StructField("municipio",
                                StructType([
                                    StructField("codigoIBGE", StringType(), True),
                                    StructField("nomeIBGE", StringType(), True),
                                    StructField("pais", StringType(), True),
                                    StructField("uf",
                                                StructType([
                                                    StructField("nome", StringType(), True),
                                                    StructField("sigla", StringType(), True)]), True)]), True),
                    StructField("naturezaJuridica",
                                StructType([
                                    StructField("codigo", StringType(), True),
                                    StructField("codigoTipo", StringType(), True),
                                    StructField("descricao", StringType(), True),
                                    StructField("descricaoTipo", StringType(), True)]),
                                True),
                    StructField("nome", StringType(), True),
                    StructField("nomeBairro", StringType(), True),
                    StructField("nomeFantasiaReceita", StringType(), True),
                    StructField("numeroCEP", StringType(), True),
                    StructField("numeroEndereco", StringType(), True),
                    StructField("numeroInscricaoSocial", StringType(), True),
                    StructField("numeroTelefone", StringType(), True),
                    StructField("razaoSocialReceita", StringType(), True),
                    StructField("tipoCodigo", StringType(), True),
                    StructField("tipoPessoa", StringType(), True)]), True),
    StructField("id", LongType(), True),
    StructField("mesExtrato", StringType(), True),
    StructField("portador",
                StructType([
                    StructField("codigoFormatado", StringType(), True),
                    StructField("nome", StringType(), True)]), True),
    StructField("tipoCartao",
                StructType([
                    StructField("codigo", StringType(), True),
                    StructField("descricao", StringType(), True),
                    StructField("id", LongType(), True)]), True),
    StructField("unidadeGestora",
                StructType([
                    StructField("codigo", StringType(), True),
                    StructField("nome", StringType(), True),
                    StructField("orgaoVinculado",
                                StructType([StructField("cnpj", StringType(), True),
                                            StructField("codigoSIAFI", StringType(),
                                                        True),
                                            StructField("descricaoPoder", StringType(),
                                                        True),
                                            StructField("nome", StringType(), True),
                                            StructField("orgaoMaximo",
                                                        StructType([
                                                            StructField("codigo", StringType(),
                                                                        True),
                                                            StructField("nome", StringType(), True),
                                                            StructField("sigla", StringType(),
                                                                        True)]), True),
                                            StructField("sigla", StringType(), True)]),
                                True)]), True),
    StructField("valorTransacao", StringType(), True)])
