from pyspark.sql.types import StructField, StructType, StringType, LongType


class Schemas:
    expenses_agency_columns = ["`Código Órgão` as agency_code",
                               "`Órgão` as agency",
                               "`Código Unidade Gestora` as branch_code",
                               "`Unidade Gestora` as branch",
                               "`Código Órgão Superior` as highest_department_code",
                               "`Órgão Superior` as highest_department"]

    expenses_vendor_columns = ["`Código Favorecido` as vendor_code",
                               "`Favorecido` as vendor_name"]

    expense_type_columns = ["`Código Categoria de Despesa` as expense_type_code",
                            "`Categoria de Despesa` as expense_type",
                            "`Código Grupo de Despesa` as expense_group_code",
                            "`Grupo de Despesa` as expense_group",
                            "`Código Modalidade de Aplicação` as investment_type_code",
                            "`Modalidade de Aplicação` as investment_type",
                            "`Código Elemento de Despesa` as expense_element_code",
                            "`Elemento de Despesa` as expense_element",
                            "`Código SubElemento de Despesa` as expense_sub_element_code",
                            "`SubElemento de Despesa` as expense_sub_element"
                            ]

    voucher_vendor_columns = ["estabelecimento.cnae.classe as cnae_class",
                              "estabelecimento.cnae.codigoClasse as cnae_class_code",
                              "estabelecimento.cnae.codigoDivisao as cnae_division_class",
                              "estabelecimento.cnae.codigoGrupo as cnae_group_code",
                              "estabelecimento.cnae.codigoSecao as cnae_section_code",
                              "estabelecimento.cnae.codigoSubclasse as cnae_sub_class_code",
                              "estabelecimento.cnae.divisao as cnae_division",
                              "estabelecimento.cnae.grupo as cnae_group",
                              "estabelecimento.cnae.secao as cnae_section",
                              "estabelecimento.cnae.subclasse as cnae_subclass",
                              "estabelecimento.codigoFormatado as vendor_code",
                              "estabelecimento.complementoEndereco as address_compliment",
                              "estabelecimento.dataAbertura as opening_date",
                              "estabelecimento.descricaoLogradouro as street_name",
                              "estabelecimento.enderecoEletronico as email",
                              "estabelecimento.municipio.codigoIBGE as city_code",
                              "estabelecimento.municipio.nomeIBGE as city_name",
                              "estabelecimento.municipio.pais as country",
                              "estabelecimento.municipio.uf.nome as state_name",
                              "estabelecimento.municipio.uf.sigla as state",
                              "estabelecimento.nome as vendor_legal_name",
                              "estabelecimento.nomeBairro as neighborhood_name",
                              "estabelecimento.nomeFantasiaReceita as vendor_name",
                              "estabelecimento.numeroCEP as zipcode",
                              "estabelecimento.numeroEndereco as street_number"]

    voucher_agency_columns = ["unidadeGestora.codigo as branch_code",
                              "unidadeGestora.nome as branch",
                              "unidadeGestora.orgaoVinculado.cnpj as agency_document_number",
                              "unidadeGestora.orgaoVinculado.codigoSIAFI as agency_code",
                              "unidadeGestora.orgaoVinculado.descricaoPoder as agency_state_power",
                              "unidadeGestora.orgaoVinculado.nome as agency",
                              "unidadeGestora.orgaoVinculado.orgaoMaximo.codigo as highest_department_code",
                              "unidadeGestora.orgaoVinculado.orgaoMaximo.nome as highest_department",
                              "unidadeGestora.orgaoVinculado.orgaoMaximo.sigla as highest_department_acronym"]

    voucher_city_columns = ["estabelecimento.municipio.codigoIBGE as city_code",
                            "estabelecimento.municipio.nomeIBGE as city",
                            "estabelecimento.municipio.pais as country",
                            "estabelecimento.municipio.uf.nome as state",
                            "estabelecimento.municipio.uf.sigla as state_acronym"]

    city_keys = ["city_code",
                 "city",
                 "country",
                 "state",
                 "state_acronym"]
    expense_type_keys = ["expense_type_code",
                         "expense_group_code",
                         "investment_type_code",
                         "expense_element_code",
                         "expense_sub_element_code",
                         ]
    vendor_keys = ["vendor_code",
                   "vendor_name"]
    agency_keys = ["branch_code",
                   "agency_code",
                   "highest_department_code"]

    commitment_fact_columns = ["`Id Empenho` as commitment_id",
                         "`Código Empenho` as commitment_code",
                         "to_date(`Data Emissão`, 'dd/MM/yyyy') as commitment_date",
                         "cast(regexp_replace(`Valor Original do Empenho`, ',', '\.') as double) as commitment_amount",
                         "cast(regexp_replace(`Valor do Empenho Convertido pra R$`, ',', '\.') as double) as amount_in_rs",
                         "cast(regexp_replace(`Valor Utilizado na Conversão`, ',', '\.') as double) as conversion_rate",
                         "`Tipo Documento` as document_type",
                         "`Tipo Empenho` as commitment_type",
                         "`Espécie Empenho` as commitment_currency",
                         "`Código Órgão Superior` as highest_department_code",
                         "`Código Órgão` as agency_code",
                         "`Órgão` as agency",
                         "`Código Unidade Gestora` as branch_code",
                         "`Código Favorecido` as vendor_code",
                         "`Favorecido` as vendor_name",
                         "`Modalidade de Licitação` as bidding_mode",
                         "year(to_date(`Data Emissão`, 'dd/MM/yyyy')) as year",
                         "month(to_date(`Data Emissão`, 'dd/MM/yyyy')) as month"]

    voucher_schema = StructType([
        StructField("dataTransacao", StringType(), True),
        StructField("estabelecimento",
                    StructType([
                        StructField("cnae",
                                    StructType([
                                        StructField("classe", StringType(), True),
                                        StructField("codigoClasse", StringType(), True),
                                        StructField("codigoDivisao", StringType(), True),
                                        StructField("codigoGrupo", StringType(), True),
                                        StructField("codigoSecao", StringType(), True),
                                        StructField("codigoSubclasse", StringType(), True),
                                        StructField("divisao", StringType(), True),
                                        StructField("grupo", StringType(), True),
                                        StructField("secao", StringType(), True),
                                        StructField("subclasse", StringType(), True)]), True),
                        StructField("codigoFormatado", StringType(), True),
                        StructField("complementoEndereco", StringType(), True),
                        StructField("dataAbertura", StringType(), True),
                        StructField("descricaoLogradouro", StringType(), True),
                        StructField("enderecoEletronico", StringType(), True),
                        StructField("localidadePessoa", StringType(), True),
                        StructField("municipio",
                                    StructType([
                                        StructField("codigoIBGE", StringType(), True),
                                        StructField("nomeIBGE", StringType(), True),
                                        StructField("pais", StringType(), True),
                                        StructField("uf",
                                                    StructType([
                                                        StructField("nome", StringType(), True),
                                                        StructField("sigla", StringType(), True)]), True)]), True),
                        StructField("naturezaJuridica",
                                    StructType([
                                        StructField("codigo", StringType(), True),
                                        StructField("codigoTipo", StringType(), True),
                                        StructField("descricao", StringType(), True),
                                        StructField("descricaoTipo", StringType(), True)]),
                                    True),
                        StructField("nome", StringType(), True),
                        StructField("nomeBairro", StringType(), True),
                        StructField("nomeFantasiaReceita", StringType(), True),
                        StructField("numeroCEP", StringType(), True),
                        StructField("numeroEndereco", StringType(), True),
                        StructField("numeroInscricaoSocial", StringType(), True),
                        StructField("numeroTelefone", StringType(), True),
                        StructField("razaoSocialReceita", StringType(), True),
                        StructField("tipoCodigo", StringType(), True),
                        StructField("tipoPessoa", StringType(), True)]), True),
        StructField("id", LongType(), True),
        StructField("mesExtrato", StringType(), True),
        StructField("portador",
                    StructType([
                        StructField("codigoFormatado", StringType(), True),
                        StructField("nome", StringType(), True)]), True),
        StructField("tipoCartao",
                    StructType([
                        StructField("codigo", StringType(), True),
                        StructField("descricao", StringType(), True),
                        StructField("id", LongType(), True)]), True),
        StructField("unidadeGestora",
                    StructType([
                        StructField("codigo", StringType(), True),
                        StructField("nome", StringType(), True),
                        StructField("orgaoVinculado",
                                    StructType([StructField("cnpj", StringType(), True),
                                                StructField("codigoSIAFI", StringType(),
                                                            True),
                                                StructField("descricaoPoder", StringType(),
                                                            True),
                                                StructField("nome", StringType(), True),
                                                StructField("orgaoMaximo",
                                                            StructType([
                                                                StructField("codigo", StringType(),
                                                                            True),
                                                                StructField("nome", StringType(), True),
                                                                StructField("sigla", StringType(),
                                                                            True)]), True),
                                                StructField("sigla", StringType(), True)]),
                                    True)]), True),
        StructField("valorTransacao", StringType(), True)])
