drop table if exists stage_dm_municipio;
CREATE TABLE stage_dm_municipio(cod_ibge_municipio varchar,
                          nome_ibge_municipio varchar,
                          pais varchar,
                          nome_uf varchar,
                          sigla_uf varchar);
                         
drop table if exists stage_dm_unidade_gestora;
CREATE TABLE stage_dm_unidade_gestora(cod_unidade_gestora varchar,
                                nome_unidade_gestora varchar,
                                cnpj_orgao_vinculado varchar,
                                cod_siafi_orgao_vinculado varchar,
                                desc_poder_orgao_vinculado varchar,
                                cod_orgao_maximo varchar,
                                nome_orgao_vinculado varchar,
                                nome_orgao_maximo varchar,
                                sigla_orgao_maximo varchar);
drop table if exists stage_dm_estabelecimento;
CREATE TABLE stage_dm_estabelecimento(classe_cnae varchar,
                                cod_classe_cnae varchar,
                                cod_divisao_cnae varchar,
                                cod_grupo_cnae varchar,
                                cod_secao_cnae varchar,
                                cod_sub_classe_cnae varchar,
                                divisao_cnae varchar,
                                grupo_cnae varchar,
                                secao_cnae varchar,
                                subclasse_cnae varchar,
                                cpf_cnpj varchar,
                                compl_endereco varchar,
                                data_abertura varchar,
                                desc_logradouro varchar,
                                email varchar,
                                localidade varchar,
                                cod_ibge_municipio varchar,
                                nome_ibge_municipio varchar,
                                pais varchar,
                                nome_uf varchar,
                                cod_nat_juridica varchar,
                                cod_tipo_nat_juridica varchar,
                                desc_nat_juridica varchar,
                                desc_tipo_nat_juridica varchar,
                                nome varchar,
                                nome_bairro varchar,
                                nome_fantasia varchar,
                                cep varchar,
                                numero_rua varchar,
                                numero_inscr_social varchar,
                                numero_telefone varchar,
                                tipo_documento varchar,
                                sigla_uf varchar);
                               
drop table if exists stage_dm_cartao_funcionario;
CREATE TABLE stage_dm_cartao_funcionario(doc_portador varchar,
                                   nome_portador varchar,
                                   cod_tipo_cartao varchar,
                                   dsc_tipo_cartao varchar,
                                   id_tipo_cartao bigint);

drop table if exists stage_ft_pagamentos ;                                 
CREATE TABLE stage_ft_pagamentos (id_pagamento bigint,
                         data_transacao timestamp,
                         valor_transacao double precision,
                         data_abertura_estabelecimento varchar,
                         nome_estabelecimento varchar,
                         cod_cidade_estabelecimento varchar,
                         uf_estabelecimento varchar,
                         cpf_cnpj_estabelecimento varchar,
                         cpf_cnpj_portador varchar,
                         nome_portador varchar,
                         cod_tipo_cartao varchar,
                         cod_unidade_gestora varchar,
                         ano_extrato varchar,
                         mes_extrato varchar);


drop table if exists dm_municipio;
CREATE TABLE dm_municipio(cod_ibge_municipio varchar,
                          nome_ibge_municipio varchar,
                          pais varchar,
                          nome_uf varchar,
                          sigla_uf varchar);
                         
drop table if exists dm_unidade_gestora;
CREATE TABLE dm_unidade_gestora(cod_unidade_gestora varchar,
                                nome_unidade_gestora varchar,
                                cnpj_orgao_vinculado varchar,
                                cod_siafi_orgao_vinculado varchar,
                                desc_poder_orgao_vinculado varchar,
                                cod_orgao_maximo varchar,
                                nome_orgao_vinculado varchar,
                                nome_orgao_maximo varchar,
                                sigla_orgao_maximo varchar);
drop table if exists dm_estabelecimento;
CREATE TABLE dm_estabelecimento(classe_cnae varchar,
                                cod_classe_cnae varchar,
                                cod_divisao_cnae varchar,
                                cod_grupo_cnae varchar,
                                cod_secao_cnae varchar,
                                cod_sub_classe_cnae varchar,
                                divisao_cnae varchar,
                                grupo_cnae varchar,
                                secao_cnae varchar,
                                subclasse_cnae varchar,
                                cpf_cnpj varchar,
                                compl_endereco varchar,
                                data_abertura varchar,
                                desc_logradouro varchar,
                                email varchar,
                                localidade varchar,
                                cod_ibge_municipio varchar,
                                nome_ibge_municipio varchar,
                                pais varchar,
                                nome_uf varchar,
                                cod_nat_juridica varchar,
                                cod_tipo_nat_juridica varchar,
                                desc_nat_juridica varchar,
                                desc_tipo_nat_juridica varchar,
                                nome varchar,
                                nome_bairro varchar,
                                nome_fantasia varchar,
                                cep varchar,
                                numero_rua varchar,
                                numero_inscr_social varchar,
                                numero_telefone varchar,
                                tipo_documento varchar,
                                sigla_uf varchar);
                               
drop table if exists dm_cartao_funcionario;
CREATE TABLE dm_cartao_funcionario(doc_portador varchar,
                                   nome_portador varchar,
                                   cod_tipo_cartao varchar,
                                   dsc_tipo_cartao varchar,
                                   id_tipo_cartao bigint);

drop table if exists ft_pagamentos ;                                 
CREATE TABLE ft_pagamentos (id_pagamento bigint,
                         data_transacao timestamp,
                         valor_transacao double precision,
                         data_abertura_estabelecimento varchar,
                         nome_estabelecimento varchar,
                         cod_cidade_estabelecimento varchar,
                         uf_estabelecimento varchar,
                         cpf_cnpj_estabelecimento varchar,
                         cpf_cnpj_portador varchar,
                         nome_portador varchar,
                         cod_tipo_cartao varchar,
                         cod_unidade_gestora varchar,
                         ano_extrato varchar,
                         mes_extrato varchar);
